name: Release

on:
  workflow_dispatch: {}

jobs:
  release:
    permissions:
      contents: write
    uses: adamhl8/configs/.github/workflows/release.yml@main
    with:
      setup: |
        sudo apt update
        sudo apt install -y fontforge ttfautohint
        curl -LsSf https://astral.sh/uv/install.sh | sh
    secrets: inherit
