name: Release

on:
  workflow_dispatch: {}

jobs:
  release:
    permissions:
      contents: write
    uses: adamhl8/configs/.github/workflows/release.yml@main
    secrets: inherit

  tag:
    needs: release
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 0

      - name: Get release tag
        id: tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"

  fonts:
    needs: tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TAG: ${{ needs.tag.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ needs.tag.outputs.tag }}

      - name: Set up nub
        uses: nubjs/setup-nub@v0
        with:
          node-version: "26"

      - name: Install font tools
        run: |
          sudo apt update
          sudo apt install -y fontforge ttfautohint

      - name: Set up uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990

      - name: nub install
        run: nub i --ignore-scripts

      - name: Build fonts
        run: nub src/index.ts

      - name: Attach TTFs to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload "${TAG}" ./out/*.ttf --clobber
